name: Python checks
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - run: pip install -r requirements.txt || true
      - run: pip install pytest black flake8
      - run: black --check --exclude "\.venv|__pycache__" .
      - run: flake8 . --exclude .venv,__pycache__
      - run: pytest -v
